//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamCSG_Helpdesk_2013.TeamCSG_Helpdesk_2013_HelpdeskList_VisualWebPart {
    using Microsoft.SharePoint.WebPartPages;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.SessionState;
    using System.Web.DynamicData;
    using System.Configuration;
    using System;
    using System.Collections.Specialized;
    using System.Collections;
    using System.Xml.Linq;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using System.Web.UI;
    using System.Web;
    using System.Text.RegularExpressions;
    using System.Web.Caching;
    using TeamCSG_Helpdesk_2013.Utility;
    using Telerik.Web.UI;
    using System.Linq;
    using System.Web.Profile;
    using System.Web.UI.WebControls.Expressions;
    using System.Web.Security;
    using Microsoft.SharePoint.WebControls;
    using Microsoft.SharePoint.Utilities;
    using Microsoft.SharePoint;
    using System.Text;
    using System.Collections.Generic;
    
    
    public partial class TeamCSG_Helpdesk_2013_HelpdeskList_VisualWebPart {
        
        protected global::System.Web.UI.WebControls.HiddenField gvHiddenField;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnExpandedGridIds;
        
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        
        protected global::System.Web.UI.WebControls.Button btnClearFilters;
        
        protected global::System.Web.UI.WebControls.Button btnNewItem;
        
        protected global::TeamCSG_Helpdesk_2013.Utility.CSGRadGrid gvOuter;
        
        public static implicit operator global::System.Web.UI.TemplateControl(TeamCSG_Helpdesk_2013_HelpdeskList_VisualWebPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlgvHiddenField() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.gvHiddenField = @__ctrl;
            @__ctrl.ID = "gvHiddenField";
            @__ctrl.Value = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnExpandedGridIds() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnExpandedGridIds = @__ctrl;
            @__ctrl.ID = "hdnExpandedGridIds";
            @__ctrl.Value = "";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtSearch() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtSearch = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtSearch";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Search the Helpdesk.");
            @__ctrl.AutoPostBack = true;
            @__ctrl.ToolTip = "Search Helpdesk";
            @__ctrl.Font.Names = new string[] {
                    "Calibri"};
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "margin-bottom: 10px");
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(250D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.TextChanged -= new System.EventHandler(this.txtName_TextChanged);
            @__ctrl.TextChanged += new System.EventHandler(this.txtName_TextChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnClearFilters() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnClearFilters = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnClearFilters";
            @__ctrl.CssClass = "csgbutton";
            @__ctrl.Text = "Clear Filters";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "margin-right:10px;display:inline-block;");
            @__ctrl.Click -= new System.EventHandler(this.btnClearFilters_Click);
            @__ctrl.Click += new System.EventHandler(this.btnClearFilters_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnNewItem() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnNewItem = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnNewItem";
            @__ctrl.CssClass = "csgbutton";
            @__ctrl.Text = "New Item";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "margin-right:10px;display:inline-block;");
            @__ctrl.Click -= new System.EventHandler(this.btnNewItem_Click);
            @__ctrl.Click += new System.EventHandler(this.btnNewItem_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control3(Telerik.Web.UI.GridResizing @__ctrl) {
            @__ctrl.AllowColumnResize = false;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control4(Telerik.Web.UI.GridSelecting @__ctrl) {
            @__ctrl.AllowRowSelect = false;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control2(Telerik.Web.UI.GridClientSettings @__ctrl) {
            this.@__BuildControl__control3(@__ctrl.Resizing);
            this.@__BuildControl__control4(@__ctrl.Selecting);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control10(Telerik.Web.UI.GridGroupingSettings @__ctrl) {
            @__ctrl.GroupContinuesFormatString = "";
            @__ctrl.GroupContinuedFormatString = "";
            @__ctrl.GroupSplitDisplayFormat = "";
            @__ctrl.GroupSplitFormat = "";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control12(System.Web.UI.Control @__ctrl) {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control13(Telerik.Web.UI.GridCommandItemSettings @__ctrl) {
            @__ctrl.ShowAddNewRecordButton = false;
            @__ctrl.ShowRefreshButton = false;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.GridGroupByField @__BuildControl__control17() {
            global::Telerik.Web.UI.GridGroupByField @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.GridGroupByField();
            @__ctrl.FieldAlias = "StatusName";
            @__ctrl.FieldName = "StatusName";
            @__ctrl.HeaderText = "Status";
            @__ctrl.HeaderValueSeparator = ": ";
            @__ctrl.FormatString = "<strong>{0}</strong>";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control16(Telerik.Web.UI.GridGroupByFieldList @__ctrl) {
            global::Telerik.Web.UI.GridGroupByField @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control17();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.GridGroupByField @__BuildControl__control19() {
            global::Telerik.Web.UI.GridGroupByField @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.GridGroupByField();
            @__ctrl.FieldName = "StatusName";
            @__ctrl.SortOrder = global::Telerik.Web.UI.GridSortOrder.Ascending;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control18(Telerik.Web.UI.GridGroupByFieldList @__ctrl) {
            global::Telerik.Web.UI.GridGroupByField @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control19();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.GridGroupByExpression @__BuildControl__control15() {
            global::Telerik.Web.UI.GridGroupByExpression @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.GridGroupByExpression();
            this.@__BuildControl__control16(@__ctrl.SelectFields);
            this.@__BuildControl__control18(@__ctrl.GroupByFields);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control14(Telerik.Web.UI.GridGroupByExpressionCollection @__ctrl) {
            global::Telerik.Web.UI.GridGroupByExpression @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control15();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control23() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblID";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control23);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public void @__DataBinding__control23(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Label dataBindingExpressionBuilderTarget;
            Telerik.Web.UI.GridItem Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Label)(sender));
            Container = ((Telerik.Web.UI.GridItem)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString( Eval("RowId") , global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control22(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control23();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control24(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(50D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control25(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(50D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.GridTemplateColumn @__BuildControl__control21() {
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.GridTemplateColumn();
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control22), null);
            @__ctrl.DataField = "RowId";
            @__ctrl.HeaderText = "Item ID";
            @__ctrl.AllowSorting = true;
            @__ctrl.AllowFiltering = false;
            this.@__BuildControl__control24(@__ctrl.HeaderStyle);
            this.@__BuildControl__control25(@__ctrl.ItemStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControl__control28() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblTitle";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control28);
            @__ctrl.Click -= new System.EventHandler(this.lblTitle_Click);
            @__ctrl.Click += new System.EventHandler(this.lblTitle_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public void @__DataBinding__control28(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.LinkButton dataBindingExpressionBuilderTarget;
            Telerik.Web.UI.GridItem Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.LinkButton)(sender));
            Container = ((Telerik.Web.UI.GridItem)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.CommandArgument = global::System.Convert.ToString( Eval("RowId") , global::System.Globalization.CultureInfo.CurrentCulture);
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString( Eval("Title") , global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control27(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control28();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control29(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control30(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.GridTemplateColumn @__BuildControl__control26() {
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.GridTemplateColumn();
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control27), null);
            @__ctrl.DataField = "Title";
            @__ctrl.HeaderText = "Title";
            @__ctrl.AllowSorting = true;
            @__ctrl.SortExpression = "Title";
            @__ctrl.AllowFiltering = false;
            this.@__BuildControl__control29(@__ctrl.HeaderStyle);
            this.@__BuildControl__control30(@__ctrl.ItemStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control33() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblCategory";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control33);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public void @__DataBinding__control33(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Label dataBindingExpressionBuilderTarget;
            Telerik.Web.UI.GridItem Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Label)(sender));
            Container = ((Telerik.Web.UI.GridItem)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString( Eval("CategoryName") , global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control32(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control33();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.RadComboBox @__BuildControl__control35() {
            global::Telerik.Web.UI.RadComboBox @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.RadComboBox();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlCategoryFilter";
            @__ctrl.OnClientSelectedIndexChanged = "ddlCategoryIndexChanged";
            @__ctrl.AllowCustomText = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control34(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::Telerik.Web.UI.RadComboBox @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control35();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                 "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control36(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(175D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control37(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(175D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.GridTemplateColumn @__BuildControl__control31() {
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.GridTemplateColumn();
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control32), null);
            @__ctrl.FilterTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control34), null);
            @__ctrl.DataField = "CategoryId";
            @__ctrl.UniqueName = "CategoryId";
            @__ctrl.HeaderText = "Category";
            @__ctrl.AllowSorting = true;
            @__ctrl.SortExpression = "CategoryName";
            this.@__BuildControl__control36(@__ctrl.HeaderStyle);
            this.@__BuildControl__control37(@__ctrl.ItemStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control40() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblAssignedTo";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control40);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public void @__DataBinding__control40(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Label dataBindingExpressionBuilderTarget;
            Telerik.Web.UI.GridItem Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Label)(sender));
            Container = ((Telerik.Web.UI.GridItem)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString( Eval("AssignedToUserTitle") , global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control39(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control40();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.RadComboBox @__BuildControl__control42() {
            global::Telerik.Web.UI.RadComboBox @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.RadComboBox();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlAssignedToFilter";
            @__ctrl.OnClientSelectedIndexChanged = "ddlAssignedToIndexChanged";
            @__ctrl.AllowCustomText = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control41(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::Telerik.Web.UI.RadComboBox @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control42();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                 "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control43(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(175D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control44(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(175D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.GridTemplateColumn @__BuildControl__control38() {
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.GridTemplateColumn();
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control39), null);
            @__ctrl.FilterTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control41), null);
            @__ctrl.DataField = "AssignedToId";
            @__ctrl.UniqueName = "AssignedToId";
            @__ctrl.HeaderText = "Assigned To";
            @__ctrl.AllowSorting = true;
            @__ctrl.SortExpression = "AssignedToUserTitle";
            @__ctrl.AllowFiltering = true;
            this.@__BuildControl__control43(@__ctrl.HeaderStyle);
            this.@__BuildControl__control44(@__ctrl.ItemStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control47() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblStatus";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control47);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public void @__DataBinding__control47(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Label dataBindingExpressionBuilderTarget;
            Telerik.Web.UI.GridItem Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Label)(sender));
            Container = ((Telerik.Web.UI.GridItem)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString( Eval("StatusName") , global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control46(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control47();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.RadComboBox @__BuildControl__control49() {
            global::Telerik.Web.UI.RadComboBox @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.RadComboBox();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlStatusFilter";
            @__ctrl.OnClientSelectedIndexChanged = "ddlStatusIndexChanged";
            @__ctrl.AllowCustomText = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control48(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::Telerik.Web.UI.RadComboBox @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control49();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                 "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control50(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(175D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control51(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(175D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.GridTemplateColumn @__BuildControl__control45() {
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.GridTemplateColumn();
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control46), null);
            @__ctrl.FilterTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control48), null);
            @__ctrl.DataField = "StatusId";
            @__ctrl.UniqueName = "StatusId";
            @__ctrl.HeaderText = "Status";
            @__ctrl.AllowSorting = true;
            @__ctrl.SortExpression = "StatusName";
            this.@__BuildControl__control50(@__ctrl.HeaderStyle);
            this.@__BuildControl__control51(@__ctrl.ItemStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control54() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblPriority";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control54);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public void @__DataBinding__control54(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Label dataBindingExpressionBuilderTarget;
            Telerik.Web.UI.GridItem Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Label)(sender));
            Container = ((Telerik.Web.UI.GridItem)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString( Eval("PriorityName") , global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control53(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control54();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.RadComboBox @__BuildControl__control56() {
            global::Telerik.Web.UI.RadComboBox @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.RadComboBox();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlPriorityFilter";
            @__ctrl.OnClientSelectedIndexChanged = "ddlPriorityIndexChanged";
            @__ctrl.AllowCustomText = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control55(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::Telerik.Web.UI.RadComboBox @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control56();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                 "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control57(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(175D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control58(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(175D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.GridTemplateColumn @__BuildControl__control52() {
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.GridTemplateColumn();
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control53), null);
            @__ctrl.FilterTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control55), null);
            @__ctrl.DataField = "PriorityId";
            @__ctrl.UniqueName = "PriorityId";
            @__ctrl.HeaderText = "Priority";
            @__ctrl.AllowSorting = true;
            @__ctrl.SortExpression = "PriorityName";
            this.@__BuildControl__control57(@__ctrl.HeaderStyle);
            this.@__BuildControl__control58(@__ctrl.ItemStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control61() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblDescription";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control61);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public void @__DataBinding__control61(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Label dataBindingExpressionBuilderTarget;
            Telerik.Web.UI.GridItem Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Label)(sender));
            Container = ((Telerik.Web.UI.GridItem)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString( MakeShort(Convert.ToString(Eval("Description"))) , global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control60(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control61();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                 <HeaderStyle Width=\"50px\" />\r\n                <ItemStyle Width" +
                        "=\"50px\" />\r\n                "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.GridTemplateColumn @__BuildControl__control59() {
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.GridTemplateColumn();
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control60), null);
            @__ctrl.DataField = "Description";
            @__ctrl.HeaderText = "Description";
            @__ctrl.AllowSorting = true;
            @__ctrl.SortExpression = "Description";
            @__ctrl.AllowFiltering = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control64() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblCreatedBy";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control64);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public void @__DataBinding__control64(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Label dataBindingExpressionBuilderTarget;
            Telerik.Web.UI.GridItem Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Label)(sender));
            Container = ((Telerik.Web.UI.GridItem)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString( Eval("CreatedByUserTitle") , global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control63(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control64();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control65(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control66(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.GridTemplateColumn @__BuildControl__control62() {
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.GridTemplateColumn();
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control63), null);
            @__ctrl.DataField = "CreatedById";
            @__ctrl.HeaderText = "Created By";
            @__ctrl.AllowSorting = true;
            @__ctrl.SortExpression = "CreatedByUserTitle";
            @__ctrl.AllowFiltering = false;
            this.@__BuildControl__control65(@__ctrl.HeaderStyle);
            this.@__BuildControl__control66(@__ctrl.ItemStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control69() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblModifiedBy";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control69);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public void @__DataBinding__control69(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Label dataBindingExpressionBuilderTarget;
            Telerik.Web.UI.GridItem Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Label)(sender));
            Container = ((Telerik.Web.UI.GridItem)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString( Eval("ModifiedByUserTitle") , global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control68(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control69();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control70(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control71(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.GridTemplateColumn @__BuildControl__control67() {
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.GridTemplateColumn();
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control68), null);
            @__ctrl.DataField = "ModifiedById";
            @__ctrl.HeaderText = "Modified By";
            @__ctrl.AllowSorting = true;
            @__ctrl.SortExpression = "ModifiedByUserTitle";
            @__ctrl.AllowFiltering = false;
            this.@__BuildControl__control70(@__ctrl.HeaderStyle);
            this.@__BuildControl__control71(@__ctrl.ItemStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control74() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblCreated";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control74);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public void @__DataBinding__control74(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Label dataBindingExpressionBuilderTarget;
            Telerik.Web.UI.GridItem Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Label)(sender));
            Container = ((Telerik.Web.UI.GridItem)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString( Eval("Created", "{0:d}") , global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control73(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control74();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control75(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(75D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control76(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(75D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.GridTemplateColumn @__BuildControl__control72() {
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.GridTemplateColumn();
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control73), null);
            @__ctrl.DataField = "Created";
            @__ctrl.HeaderText = "Created";
            @__ctrl.AllowSorting = true;
            @__ctrl.SortExpression = "Created";
            @__ctrl.AllowFiltering = false;
            this.@__BuildControl__control75(@__ctrl.HeaderStyle);
            this.@__BuildControl__control76(@__ctrl.ItemStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control79() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblModified";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control79);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public void @__DataBinding__control79(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Label dataBindingExpressionBuilderTarget;
            Telerik.Web.UI.GridItem Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Label)(sender));
            Container = ((Telerik.Web.UI.GridItem)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString( Eval("Modified", "{0:d}") , global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control78(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control79();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control80(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(75D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control81(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(75D, global::System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.GridTemplateColumn @__BuildControl__control77() {
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.GridTemplateColumn();
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control78), null);
            @__ctrl.DataField = "Modified";
            @__ctrl.HeaderText = "Modified";
            @__ctrl.AllowSorting = true;
            @__ctrl.SortExpression = "Modified";
            @__ctrl.AllowFiltering = false;
            this.@__BuildControl__control80(@__ctrl.HeaderStyle);
            this.@__BuildControl__control81(@__ctrl.ItemStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control20(Telerik.Web.UI.GridColumnCollection @__ctrl) {
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control21();
            @__ctrl.Add(@__ctrl1);
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control26();
            @__ctrl.Add(@__ctrl2);
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control31();
            @__ctrl.Add(@__ctrl3);
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control38();
            @__ctrl.Add(@__ctrl4);
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl5;
            @__ctrl5 = this.@__BuildControl__control45();
            @__ctrl.Add(@__ctrl5);
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl6;
            @__ctrl6 = this.@__BuildControl__control52();
            @__ctrl.Add(@__ctrl6);
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl7;
            @__ctrl7 = this.@__BuildControl__control59();
            @__ctrl.Add(@__ctrl7);
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl8;
            @__ctrl8 = this.@__BuildControl__control62();
            @__ctrl.Add(@__ctrl8);
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl9;
            @__ctrl9 = this.@__BuildControl__control67();
            @__ctrl.Add(@__ctrl9);
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl10;
            @__ctrl10 = this.@__BuildControl__control72();
            @__ctrl.Add(@__ctrl10);
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl11;
            @__ctrl11 = this.@__BuildControl__control77();
            @__ctrl.Add(@__ctrl11);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control11(Telerik.Web.UI.GridTableView @__ctrl) {
            @__ctrl.NoRecordsTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control12));
            @__ctrl.CommandItemDisplay = global::Telerik.Web.UI.GridCommandItemDisplay.Top;
            @__ctrl.EditMode = global::Telerik.Web.UI.GridEditMode.InPlace;
            @__ctrl.DataKeyNames = new string[] {
                    "RowId",
                    "StatusId"};
            @__ctrl.AllowFilteringByColumn = true;
            this.@__BuildControl__control13(@__ctrl.CommandItemSettings);
            this.@__BuildControl__control14(@__ctrl.GroupByExpressions);
            this.@__BuildControl__control20(@__ctrl.Columns);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::TeamCSG_Helpdesk_2013.Utility.CSGRadGrid @__BuildControl__control9() {
            global::TeamCSG_Helpdesk_2013.Utility.CSGRadGrid @__ctrl;
            @__ctrl = new global::TeamCSG_Helpdesk_2013.Utility.CSGRadGrid();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "gvHelpdesk";
            @__ctrl.MasterTableView.NoDetailRecordsText = "";
            @__ctrl.EnableLinqExpressions = false;
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.ClientSettings.AllowGroupExpandCollapse = true;
            @__ctrl.AllowSorting = true;
            @__ctrl.AllowPaging = true;
            @__ctrl.PageSize = 20;
            @__ctrl.AlternatingItemStyle.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(184, 207, 255)));
            @__ctrl.HeaderStyle.CssClass = "gridheader";
            this.@__BuildControl__control10(@__ctrl.GroupingSettings);
            this.@__BuildControl__control11(@__ctrl.MasterTableView);
            @__ctrl.ItemDataBound -= new Telerik.Web.UI.GridItemEventHandler(this.gvHelpdesk_ItemDataBound);
            @__ctrl.ItemDataBound += new Telerik.Web.UI.GridItemEventHandler(this.gvHelpdesk_ItemDataBound);
            @__ctrl.PreRender -= new System.EventHandler(this.gvHelpdesk_PreRender);
            @__ctrl.PreRender += new System.EventHandler(this.gvHelpdesk_PreRender);
            @__ctrl.ItemCommand -= new Telerik.Web.UI.GridCommandEventHandler(this.gvHelpdesk_ItemCommand);
            @__ctrl.ItemCommand += new Telerik.Web.UI.GridCommandEventHandler(this.gvHelpdesk_ItemCommand);
            @__ctrl.SortCommand -= new Telerik.Web.UI.GridSortCommandEventHandler(this.gvHelpdesk_SortCommand);
            @__ctrl.SortCommand += new Telerik.Web.UI.GridSortCommandEventHandler(this.gvHelpdesk_SortCommand);
            @__ctrl.PageIndexChanged -= new Telerik.Web.UI.GridPageChangedEventHandler(this.gvHelpdesk_PageIndexChanged);
            @__ctrl.PageIndexChanged += new Telerik.Web.UI.GridPageChangedEventHandler(this.gvHelpdesk_PageIndexChanged);
            @__ctrl.PageSizeChanged -= new Telerik.Web.UI.GridPageSizeChangedEventHandler(this.gvHelpdesk_PageSizeChanged);
            @__ctrl.PageSizeChanged += new Telerik.Web.UI.GridPageSizeChangedEventHandler(this.gvHelpdesk_PageSizeChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control8(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    <div>            \r\n"));
            global::TeamCSG_Helpdesk_2013.Utility.CSGRadGrid @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control9();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n</div>\r\n              "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Telerik.Web.UI.GridTemplateColumn @__BuildControl__control7() {
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl;
            @__ctrl = new global::Telerik.Web.UI.GridTemplateColumn();
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control8), null);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control6(Telerik.Web.UI.GridColumnCollection @__ctrl) {
            global::Telerik.Web.UI.GridTemplateColumn @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control7();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control5(Telerik.Web.UI.GridTableView @__ctrl) {
            @__ctrl.HierarchyDefaultExpanded = true;
            @__ctrl.DataKeyNames = new string[] {
                    "StatusId"};
            @__ctrl.AlternatingItemStyle.BackColor = global::System.Drawing.Color.White;
            @__ctrl.ItemStyle.BackColor = global::System.Drawing.Color.White;
            @__ctrl.CommandItemDisplay = global::Telerik.Web.UI.GridCommandItemDisplay.None;
            @__ctrl.AllowFilteringByColumn = false;
            @__ctrl.NoMasterRecordsText = "No tasks.";
            @__ctrl.ShowFooter = false;
            this.@__BuildControl__control6(@__ctrl.Columns);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::TeamCSG_Helpdesk_2013.Utility.CSGRadGrid @__BuildControlgvOuter() {
            global::TeamCSG_Helpdesk_2013.Utility.CSGRadGrid @__ctrl;
            @__ctrl = new global::TeamCSG_Helpdesk_2013.Utility.CSGRadGrid();
            this.gvOuter = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "gvOuter";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.AllowPaging = false;
            @__ctrl.AllowSorting = false;
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.None;
            @__ctrl.ShowStatusBar = false;
            @__ctrl.ShowGroupPanel = false;
            @__ctrl.ShowHeader = false;
            @__ctrl.AlternatingItemStyle.BackColor = global::System.Drawing.Color.White;
            @__ctrl.ItemStyle.BackColor = global::System.Drawing.Color.White;
            @__ctrl.BorderWidth = new System.Web.UI.WebControls.Unit(0D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.PageSize = 500;
            @__ctrl.HeaderStyle.CssClass = "gridheader";
            this.@__BuildControl__control2(@__ctrl.ClientSettings);
            this.@__BuildControl__control5(@__ctrl.MasterTableView);
            @__ctrl.ItemDataBound -= new Telerik.Web.UI.GridItemEventHandler(this.gvOuter_ItemDataBound);
            @__ctrl.ItemDataBound += new Telerik.Web.UI.GridItemEventHandler(this.gvOuter_ItemDataBound);
            @__ctrl.NeedDataSource -= new Telerik.Web.UI.GridNeedDataSourceEventHandler(this.gvOuter_NeedDataSource);
            @__ctrl.NeedDataSource += new Telerik.Web.UI.GridNeedDataSourceEventHandler(this.gvOuter_NeedDataSource);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::TeamCSG_Helpdesk_2013.TeamCSG_Helpdesk_2013_HelpdeskList_VisualWebPart.TeamCSG_Helpdesk_2013_HelpdeskList_VisualWebPart @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n <script type=\"text/javascript\">\r\n\r\n     function ddlAssignedToIndexChanged(s" +
                        "ender, args) {\r\n         var tableView = $find(m_AssignedToTableViewId);\r\n      " +
                        "   var filterVal = args.get_item().get_value();\r\n         if (filterVal == \"All\"" +
                        ") {\r\n             tableView.filter(\"AssignedToId\", filterVal, \"NoFilter\");\r\n    " +
                        "     }\r\n         else {\r\n             filterVal = parseInt(filterVal);\r\n        " +
                        "     tableView.filter(\"AssignedToId\", filterVal, \"EqualTo\");\r\n         }\r\n     }" +
                        "\r\n     function ddlCategoryIndexChanged(sender, args) {\r\n         var tableView " +
                        "= $find(m_CategoryToTableViewId);\r\n         var filterVal = args.get_item().get_" +
                        "value();\r\n         if (filterVal == \"All\") {\r\n             tableView.filter(\"Cat" +
                        "egoryId\", filterVal, \"NoFilter\");\r\n         }\r\n         else {\r\n             tab" +
                        "leView.filter(\"CategoryId\", filterVal, \"EqualTo\");\r\n         }\r\n     }\r\n     fun" +
                        "ction ddlStatusIndexChanged(sender, args) {\r\n         var tableView = $find(m_St" +
                        "atusToTableViewId);\r\n         var filterVal = args.get_item().get_value();\r\n    " +
                        "     if (filterVal == \"All\") {\r\n             tableView.filter(\"StatusId\", filter" +
                        "Val, \"NoFilter\");\r\n         }\r\n         else {\r\n             tableView.filter(\"S" +
                        "tatusId\", filterVal, \"EqualTo\");\r\n         }\r\n     }\r\n     function ddlPriorityI" +
                        "ndexChanged(sender, args) {\r\n         var tableView = $find(m_PriorityToTableVie" +
                        "wId);\r\n         var filterVal = args.get_item().get_value();\r\n         if (filte" +
                        "rVal == \"All\") {\r\n             tableView.filter(\"PriorityId\", filterVal, \"NoFilt" +
                        "er\");\r\n         }\r\n         else {\r\n             tableView.filter(\"PriorityId\", " +
                        "filterVal, \"EqualTo\");\r\n         }\r\n     }\r\n\r\n     function hasClass(element, cl" +
                        "s) {\r\n         return (\' \' + element.className + \' \').indexOf(\' \' + cls + \' \') >" +
                        " -1;\r\n     }\r\n\r\n\r\n     function onGridCreate() {\r\n         var elements = docume" +
                        "nt.getElementsByTagName(\"tr\");\r\n            for (var i = 0; i < elements.length;" +
                        " i++) {\r\n                if (elements[i].className == \"rgPager\") {\r\n            " +
                        "        elements[i].style.visibility = \'hidden\';\r\n                    elements[i" +
                        "].style.display = \'none\';\r\n                 }\r\n            }\r\n     }\r\n\r\n     fun" +
                        "ction expandCollapseGrids(string) {\r\n         var pageElements = document.getEle" +
                        "mentsByTagName(\"tr\");\r\n         for (var n = 0; n < pageElements.length; n++) {\r" +
                        "\n             if (pageElements[n].className == \"rgPager\") {\r\n                 pa" +
                        "geElements[n].style.visibility = \'hidden\';\r\n                 pageElements[n].sty" +
                        "le.display = \'none\';\r\n             }\r\n         }\r\n\r\n         var expandedGrids =" +
                        " string.split(\'@\');\r\n         for (var i = 0; i < expandedGrids.length-1; i++) {" +
                        "\r\n                 var grid = document.getElementById(expandedGrids[i]);\r\n      " +
                        "           var elements = grid.getElementsByTagName(\"tr\");\r\n                 for" +
                        " (var j = 0; j < elements.length; j++) {\r\n                     if (elements[j].c" +
                        "lassName == \"rgPager\") {\r\n                         elements[j].style.visibility " +
                        "= \'visible\';\r\n                         elements[j].style.display = \'table-row\';\r" +
                        "\n                     }\r\n                 }\r\n             }\r\n     }\r\n\r\n</script>" +
                        "\r\n\r\n<style type=\"text/css\">\r\n    .RadGrid_Default .rgMasterTable, .RadGrid_Defau" +
                        "lt .rgDetailTable, .RadGrid_Default .rgGroupPanel table, .RadGrid_Default .rgCom" +
                        "mandRow table, .RadGrid_Default .rgEditForm table, .RadGrid_Default .rgPager tab" +
                        "le {\r\n        table-layout:fixed !important;\r\n    }\r\n</style>\r\n\r\n<div style =\"wi" +
                        "dth:100%\">\r\n"));
            global::System.Web.UI.WebControls.HiddenField @__ctrl1;
            @__ctrl1 = this.@__BuildControlgvHiddenField();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::System.Web.UI.WebControls.HiddenField @__ctrl2;
            @__ctrl2 = this.@__BuildControlhdnExpandedGridIds();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            @__ctrl3 = this.@__BuildControltxtSearch();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            <img src=\"../../_layouts/15/TeamCSG_Helpdesk_2013/images/view.png\" " +
                        "style=\"width:20px;height:20px;margin-left:3px;vertical-align:top;cursor:pointer;" +
                        "\" />\r\n            "));
            global::System.Web.UI.WebControls.Button @__ctrl4;
            @__ctrl4 = this.@__BuildControlbtnClearFilters();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            global::System.Web.UI.WebControls.Button @__ctrl5;
            @__ctrl5 = this.@__BuildControlbtnNewItem();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n</div>\r\n"));
            global::TeamCSG_Helpdesk_2013.Utility.CSGRadGrid @__ctrl6;
            @__ctrl6 = this.@__BuildControlgvOuter();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
